version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: bdd
    ports:
      - 8080:8080
    environment:
      FLASK_APP: service:app
      BINDING_CLOUDANT: '{"username":"admin","password":"pass","host":"couchdb","port":5984,"url":"http://${CLOUDANT_USERNAME}:${CLOUDANT_PASSWORD}@couchdb:5984"}'
    networks:
      - backend
    depends_on:
      - couchdb

  couchdb:
    image: couchdb:latest
    hostname: couchdb
    ports:
      - 5984:5984
    volumes:
      - couchdb:/opt/couchdb/data
    environment:
      COUCHDB_USER: ${CLOUDANT_USERNAME}
      COUCHDB_PASSWORD: ${CLOUDANT_PASSWORD}
    networks:
      - backend

  setup:
    image: couchdb:latest
    command: >
      bash -c "echo 'waiting 15 seconds for couchdb to initialize...'; sleep 15
      && curl -X PUT http://${CLOUDANT_USERNAME}:${CLOUDANT_PASSWORD}@couchdb:5984/_users
      && curl -X PUT http://${CLOUDANT_USERNAME}:${CLOUDANT_PASSWORD}@couchdb:5984/_replicator
      && curl -X PUT http://${CLOUDANT_USERNAME}:${CLOUDANT_PASSWORD}@couchdb:5984/_global_changes"
    networks:
      - backend
    depends_on:
      - couchdb   
   
volumes:
  couchdb:

networks:
  backend:

